name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code_quality:
    runs-on: ubuntu-latest
    env:
      QUICK_XML_NIF_BUILD: "1"
    name: Code Quality
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2.2"
          elixir-version: "1.18.2"

      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused

  test:
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      QUICK_XML_NIF_BUILD: "1"

    strategy:
      fail-fast: false
      matrix:
        otp: [24.3, 25.3, 26.2, 27.2]
        elixir: [1.13, 1.14, 1.15, 1.16, 1.17, 1.18]
        exclude:
          - otp: 25.3
            elixir: 1.13
          - otp: 26.2
            elixir: 1.13
          - otp: 27.2
            elixir: 1.13
          - otp: 27.2
            elixir: 1.14
          - otp: 27.2
            elixir: 1.15
          - otp: 27.2
            elixir: 1.16
          - otp: 24.3
            elixir: 1.17
          - otp: 24.3
            elixir: 1.18

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: dtolnay/rust-toolchain@stable

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        env:
          RUST_BACKTRACE: 1
      - run: mix test
