name: Build precompiled NIFs

on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.16", "2.15"]
        job:
          - { target: arm-unknown-linux-gnueabihf, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-apple-darwin, os: macos-14 }
          - { target: riscv64gc-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
          - { target: x86_64-apple-darwin, os: macOS-14 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-20.04, use-cross: true }
          - { target: x86_64-pc-windows-gnu, os: windows-2019 }
          - { target: x86_64-pc-windows-msvc, os: windows-2019 }
          - { target: x86_64-unknown-freebsd, os: ubuntu-22.04, use-cross: true, cross-version: v0.2.5 }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract project version
        shell: bash
        run: |
          # Get the project version from mix.exs
          echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.0.1
        with:
          project-name: quick_xml_nif
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          cross-version: ${{ matrix.job.cross-version || 'v0.2.4' }}
          project-dir: "native/quick_xml_nif"

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}
          overwrite: true

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')

  hex_publish:
    name: Publish to Hex.pm and HexDocs.pm
    runs-on: ubuntu-latest
    needs: build_release
    if: startsWith(github.ref, 'refs/tags/')
    env:
      QUICK_XML_NIF_BUILD: "1"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Elixir & OTP
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.2"
          otp-version: "27.2.2"

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get

      - name: Generate NIF Checksum
        run: mix rustler_precompiled.download QuickXml --all --print

      - name: Build Docs
        run: mix docs

      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes

      - name: Publish HexDocs.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish docs --yes
